// This file is an automatically generated default you can edit it as you wan
// If you delete this file, the default version might be re-generated on next build
// Generated by marmotte/vite/docs v0.0.0

import DefaultTheme from "vitepress/theme";

// see https://vitepress-sidebar.cdget.com/advanced-usage/multi-level-sidebar-with-indents
// @ts-ignore
import "marmotte/vitepress/sidebar/indent.css";

export default DefaultTheme;
